const Users = [
  {
    id: 1,
    username: "admin",
    email: "admin@scg.com",
    password: "adminadmin",
    image: "1.jpg",
    firstname: "Tapmid",
    lastname: "Humphries",
    idDepartment: 13,
    department: "HR Business Partner",
    position: "Assistant Manager-HR Business Partner",
    mobileNumber: "081-111-1111",
    workingLocation: "TPE - Rayong Site#1",
    site: 1,
    status: "active",
    company: "Thai Polyethylene Co., Ltd.",
    follower: 29078,
    following: 84392,
    authorities: ["ROLE_USER", "ROLE_ADMIN"],
  },
  {
    id: 2,
    username: "manager",
    email: "manager@scg.com",
    password: "managermanager",
    image: "2.jpg",
    firstname: "Theodor",
    lastname: "O'Moore",
    idDepartment: 13,
    department: "HR Business Partner",
    position: "Manager-HR Business Partner",
    mobileNumber: "082-222-2222",
    workingLocation: "TPE - Rayong Site#1",
    site: 1,
    status: "active",
    company: "Thai Polyethylene Co., Ltd.",
    follower: 86753,
    following: 32454,
    authorities: ["ROLE_USER", "ROLE_MANAGER"],
  },
  {
    id: 3,
    username: "user",
    email: "user@scg.com",
    password: "useruser",
    image: "3.jpg",
    firstname: "Shaunna",
    lastname: "Richard",
    idDepartment: 6,
    department: "HDPE 4 Production",
    position: "HDPE 4 Production Operator",
    mobileNumber: "083-333-3333",
    workingLocation: "TPE - Rayong Site#3",
    site: 3,
    status: "active",
    company: "Thai Polyethylene Co., Ltd.",
    follower: 9732,
    following: 4356,
    authorities: ["ROLE_USER"],
  },
  {
    id: 4,
    username: "user",
    email: "user@scg.com",
    password: "useruser",
    image: "4.jpg",
    firstname: "Shaunna",
    lastname: "Richard",
    idDepartment: 5,
    department: "Catalyst & Pilot Plant Production Department",
    position: "Catalyst Production Operator",
    mobileNumber: "083-333-3333",
    workingLocation: "TPE - Rayong Site#3",
    site: 3,
    status: "active",
    company: "Thai Polyethylene Co., Ltd.",
    follower: 9732,
    following: 4356,
    authorities: ["ROLE_USER"],
  },
  {
    id: 5,
    username: "user",
    email: "user@scg.com",
    password: "useruser",
    image: "5.jpg",
    firstname: "Shaunna",
    lastname: "Richard",
    idDepartment: 2,
    department: "Quality Assurance & Quality Control Department",
    position: "Quality Control Technician - PAL",
    mobileNumber: "083-333-3333",
    workingLocation: "TPE - Rayong Site#3",
    site: 3,
    status: "active",
    company: "Thai Polyethylene Co., Ltd.",
    follower: 9732,
    following: 4356,
    authorities: ["ROLE_USER"],
  },
  {
    id: 6,
    username: "user",
    email: "user@scg.com",
    password: "useruser",
    image: "6.jpg",
    firstname: "Sphaunna",
    lastname: "Richard",
    idDepartment: 12,
    department: "Safety, Occupational Health & Environment Department",
    position: "Occupational Health & Safety System Engineer",
    mobileNumber: "083-333-3333",
    workingLocation: "TPE - Rayong Site#3",
    site: 3,
    status: "active",
    company: "Thai Polyethylene Co., Ltd.",
    follower: 9732,
    following: 4356,
    authorities: ["ROLE_USER"],
  },
  {
    id: 7,
    username: "user",
    email: "user@scg.com",
    password: "useruser",
    image: "7.jpg",
    firstname: "Shaunna",
    lastname: "Richard",
    idDepartment: 6,
    department: "HDPE 4 Production",
    position: "HDPE 4 Production Operator",
    mobileNumber: "083-333-3333",
    workingLocation: "TPE - Rayong Site#3",
    site: 3,
    status: "active",
    company: "Thai Polyethylene Co., Ltd.",
    follower: 9732,
    following: 4356,
    authorities: ["ROLE_USER"],
  },
  {
    id: 8,
    username: "user",
    email: "user@scg.com",
    password: "useruser",
    image: "8.jpg",
    firstname: "Shaunna",
    lastname: "Richard",
    idDepartment: 6,
    department: "HDPE 4 Production",
    position: "HDPE 4 Production Operator",
    mobileNumber: "083-333-3333",
    workingLocation: "TPE - Rayong Site#3",
    site: 3,
    status: "active",
    company: "Thai Polyethylene Co., Ltd.",
    follower: 9732,
    following: 4356,
    authorities: ["ROLE_USER"],
  },
  {
    id: 9,
    username: "user",
    email: "user@scg.com",
    password: "useruser",
    image: "9.jpg",
    firstname: "Shaunna",
    lastname: "Richard",
    idDepartment: 6,
    department: "HDPE 4 Production",
    position: "HDPE 4 Production Operator",
    mobileNumber: "083-333-3333",
    workingLocation: "TPE - Rayong Site#3",
    site: 3,
    status: "active",
    company: "Thai Polyethylene Co., Ltd.",
    follower: 9732,
    following: 4356,
    authorities: ["ROLE_USER"],
  },
  {
    id: 10,
    username: "user",
    email: "user@scg.com",
    password: "useruser",
    image: "10.jpg",
    firstname: "Shaunna",
    lastname: "Richard",
    idDepartment: 6,
    department: "HDPE 4 Production",
    position: "HDPE 4 Production Operator",
    mobileNumber: "083-333-3333",
    workingLocation: "TPE - Rayong Site#3",
    site: 3,
    status: "active",
    company: "Thai Polyethylene Co., Ltd.",
    follower: 9732,
    following: 4356,
    authorities: ["ROLE_USER"],
  },
  {
    id: 11,
    username: "user",
    email: "user@scg.com",
    password: "useruser",
    image: "11.jpg",
    firstname: "Shaunna",
    lastname: "Richard",
    idDepartment: 6,
    department: "HDPE 4 Production",
    position: "HDPE 4 Production Operator",
    mobileNumber: "083-333-3333",
    workingLocation: "TPE - Rayong Site#3",
    site: 3,
    status: "active",
    company: "Thai Polyethylene Co., Ltd.",
    follower: 9732,
    following: 4356,
    authorities: ["ROLE_USER"],
  },
  {
    id: 12,
    username: "user",
    email: "user@scg.com",
    password: "useruser",
    image: "12.jpg",
    firstname: "Shaunna",
    lastname: "Richard",
    idDepartment: 6,
    department: "HDPE 4 Production",
    position: "HDPE 4 Production Operator",
    mobileNumber: "083-333-3333",
    workingLocation: "TPE - Rayong Site#3",
    site: 3,
    status: "active",
    company: "Thai Polyethylene Co., Ltd.",
    follower: 9732,
    following: 4356,
    authorities: ["ROLE_USER"],
  },
  {
    id: 13,
    username: "user",
    email: "user@scg.com",
    password: "useruser",
    image: "13.jpg",
    firstname: "Shaunna",
    lastname: "Richard",
    idDepartment: 6,
    department: "HDPE 4 Production",
    position: "HDPE 4 Production Operator",
    mobileNumber: "083-333-3333",
    workingLocation: "TPE - Rayong Site#3",
    site: 3,
    status: "active",
    company: "Thai Polyethylene Co., Ltd.",
    follower: 9732,
    following: 4356,
    authorities: ["ROLE_USER"],
  },
  {
    id: 14,
    username: "user",
    email: "user@scg.com",
    password: "useruser",
    image: "14.jpg",
    firstname: "Shaunna",
    lastname: "Richard",
    idDepartment: 6,
    department: "HDPE 4 Production",
    position: "HDPE 4 Production Operator",
    mobileNumber: "083-333-3333",
    workingLocation: "TPE - Rayong Site#3",
    site: 3,
    status: "active",
    company: "Thai Polyethylene Co., Ltd.",
    follower: 9732,
    following: 4356,
    authorities: ["ROLE_USER"],
  },
  {
    id: 15,
    username: "user",
    email: "user@scg.com",
    password: "useruser",
    image: "15.jpg",
    firstname: "Shaunna",
    lastname: "Richard",
    idDepartment: 6,
    department: "HDPE 4 Production",
    position: "HDPE 4 Production Operator",
    mobileNumber: "083-333-3333",
    workingLocation: "TPE - Rayong Site#3",
    site: 3,
    status: "active",
    company: "Thai Polyethylene Co., Ltd.",
    follower: 9732,
    following: 4356,
    authorities: ["ROLE_USER"],
  },
  {
    id: 16,
    username: "user",
    email: "user@scg.com",
    password: "useruser",
    image: "16.jpg",
    firstname: "Shaunna",
    lastname: "Richard",
    idDepartment: 6,
    department: "HDPE 4 Production",
    position: "HDPE 4 Production Operator",
    mobileNumber: "083-333-3333",
    workingLocation: "TPE - Rayong Site#3",
    site: 3,
    status: "active",
    company: "Thai Polyethylene Co., Ltd.",
    follower: 9732,
    following: 4356,
    authorities: ["ROLE_USER"],
  },
  {
    id: 17,
    username: "user",
    email: "user@scg.com",
    password: "useruser",
    image: "17.jpg",
    firstname: "Shaunna",
    lastname: "Richard",
    idDepartment: 6,
    department: "HDPE 4 Production",
    position: "HDPE 4 Production Operator",
    mobileNumber: "083-333-3333",
    workingLocation: "TPE - Rayong Site#3",
    site: 3,
    status: "active",
    company: "Thai Polyethylene Co., Ltd.",
    follower: 9732,
    following: 4356,
    authorities: ["ROLE_USER"],
  },
  {
    id: 18,
    username: "user",
    email: "user@scg.com",
    password: "useruser",
    image: "18.jpg",
    firstname: "Shaunna",
    lastname: "Richard",
    idDepartment: 6,
    department: "HDPE 4 Production",
    position: "HDPE 4 Production Operator",
    mobileNumber: "083-333-3333",
    workingLocation: "TPE - Rayong Site#3",
    site: 3,
    status: "active",
    company: "Thai Polyethylene Co., Ltd.",
    follower: 9732,
    following: 4356,
    authorities: ["ROLE_USER"],
  },
  {
    id: 19,
    username: "user",
    email: "user@scg.com",
    password: "useruser",
    image: "19.jpg",
    firstname: "Shaunna",
    lastname: "Richard",
    idDepartment: 6,
    department: "HDPE 4 Production",
    position: "HDPE 4 Production Operator",
    mobileNumber: "083-333-3333",
    workingLocation: "TPE - Rayong Site#3",
    site: 3,
    status: "active",
    company: "Thai Polyethylene Co., Ltd.",
    follower: 9732,
    following: 4356,
    authorities: ["ROLE_USER"],
  },
  {
    id: 20,
    username: "user",
    email: "user@scg.com",
    password: "useruser",
    image: "20.jpg",
    firstname: "Shaunna",
    lastname: "Richard",
    idDepartment: 6,
    department: "HDPE 4 Production",
    position: "HDPE 4 Production Operator",
    mobileNumber: "083-333-3333",
    workingLocation: "TPE - Rayong Site#3",
    site: 3,
    status: "active",
    company: "Thai Polyethylene Co., Ltd.",
    follower: 9732,
    following: 4356,
    authorities: ["ROLE_USER"],
  },
  {
    id: 21,
    username: "user",
    email: "user@scg.com",
    password: "useruser",
    image: "21.jpg",
    firstname: "Shaunna",
    lastname: "Richard",
    idDepartment: 6,
    department: "HDPE 4 Production",
    position: "HDPE 4 Production Operator",
    mobileNumber: "083-333-3333",
    workingLocation: "TPE - Rayong Site#3",
    site: 3,
    status: "active",
    company: "Thai Polyethylene Co., Ltd.",
    follower: 9732,
    following: 4356,
    authorities: ["ROLE_USER"],
  },
  {
    id: 22,
    username: "user",
    email: "user@scg.com",
    password: "useruser",
    image: "22.jpg",
    firstname: "Shaunna",
    lastname: "Richard",
    idDepartment: 6,
    department: "HDPE 4 Production",
    position: "HDPE 4 Production Operator",
    mobileNumber: "083-333-3333",
    workingLocation: "TPE - Rayong Site#3",
    site: 3,
    status: "active",
    company: "Thai Polyethylene Co., Ltd.",
    follower: 9732,
    following: 4356,
    authorities: ["ROLE_USER"],
  },
  {
    id: 23,
    username: "user",
    email: "user@scg.com",
    password: "useruser",
    image: "23.jpg",
    firstname: "Shaunna",
    lastname: "Richard",
    idDepartment: 6,
    department: "HDPE 4 Production",
    position: "HDPE 4 Production Operator",
    mobileNumber: "083-333-3333",
    workingLocation: "TPE - Rayong Site#3",
    site: 3,
    status: "active",
    company: "Thai Polyethylene Co., Ltd.",
    follower: 9732,
    following: 4356,
    authorities: ["ROLE_USER"],
  },
  {
    id: 24,
    username: "user",
    email: "user@scg.com",
    password: "useruser",
    image: "24.jpg",
    firstname: "Shaunna",
    lastname: "Richard",
    idDepartment: 6,
    department: "HDPE 4 Production",
    position: "HDPE 4 Production Operator",
    mobileNumber: "083-333-3333",
    workingLocation: "TPE - Rayong Site#3",
    site: 3,
    status: "active",
    company: "Thai Polyethylene Co., Ltd.",
    follower: 9732,
    following: 4356,
    authorities: ["ROLE_USER"],
  },
  {
    id: 25,
    username: "user",
    email: "user@scg.com",
    password: "useruser",
    image: "25.jpg",
    firstname: "Shaunna",
    lastname: "Richard",
    idDepartment: 6,
    department: "HDPE 4 Production",
    position: "HDPE 4 Production Operator",
    mobileNumber: "083-333-3333",
    workingLocation: "TPE - Rayong Site#3",
    site: 3,
    status: "active",
    company: "Thai Polyethylene Co., Ltd.",
    follower: 9732,
    following: 4356,
    authorities: ["ROLE_USER"],
  },
  {
    id: 26,
    username: "user",
    email: "user@scg.com",
    password: "useruser",
    image: "26.jpg",
    firstname: "Shaunna",
    lastname: "Richard",
    idDepartment: 6,
    department: "HDPE 4 Production",
    position: "HDPE 4 Production Operator",
    mobileNumber: "083-333-3333",
    workingLocation: "TPE - Rayong Site#3",
    site: 3,
    status: "active",
    company: "Thai Polyethylene Co., Ltd.",
    follower: 9732,
    following: 4356,
    authorities: ["ROLE_USER"],
  },
  {
    id: 27,
    username: "user",
    email: "user@scg.com",
    password: "useruser",
    image: "27.jpg",
    firstname: "Shaunna",
    lastname: "Richard",
    idDepartment: 6,
    department: "HDPE 4 Production",
    position: "HDPE 4 Production Operator",
    mobileNumber: "083-333-3333",
    workingLocation: "TPE - Rayong Site#3",
    site: 3,
    status: "active",
    company: "Thai Polyethylene Co., Ltd.",
    follower: 9732,
    following: 4356,
    authorities: ["ROLE_USER"],
  },
  {
    id: 28,
    username: "user",
    email: "user@scg.com",
    password: "useruser",
    image: "28.jpg",
    firstname: "Shaunna",
    lastname: "Richard",
    idDepartment: 6,
    department: "HDPE 4 Production",
    position: "HDPE 4 Production Operator",
    mobileNumber: "083-333-3333",
    workingLocation: "TPE - Rayong Site#3",
    site: 3,
    status: "active",
    company: "Thai Polyethylene Co., Ltd.",
    follower: 9732,
    following: 4356,
    authorities: ["ROLE_USER"],
  },
  {
    id: 29,
    username: "user",
    email: "user@scg.com",
    password: "useruser",
    image: "29.jpg",
    firstname: "Shaunna",
    lastname: "Richard",
    idDepartment: 2,
    department: "Quality Assurance & Quality Control Department",
    position: "Quality Assurance & Quality Control Department",
    mobileNumber: "083-333-3333",
    workingLocation: "TPE - Rayong Site#3",
    site: 3,
    status: "active",
    company: "Thai Polyethylene Co., Ltd.",
    follower: 9732,
    following: 4356,
    authorities: ["ROLE_USER"],
  },
  {
    id: 30,
    username: "user",
    email: "user@scg.com",
    password: "useruser",
    image: "30.jpg",
    firstname: "Shaunna",
    lastname: "Richard",
    idDepartment: 6,
    department: "HDPE 4 Production",
    position: "HDPE 4 Production Operator",
    mobileNumber: "083-333-3333",
    workingLocation: "TPE - Rayong Site#3",
    site: 3,
    status: "terminate",
    company: "Thai Polyethylene Co., Ltd.",
    follower: 9732,
    following: 4356,
    authorities: ["ROLE_USER"],
  },
];
module.exports = Users;
