const Users = [
  {
    id: 1,
    username: "admin",
    email: "admin@scg.com",
    password: "adminadmin",
    image: "admin.jpg",
    firstname: "Tahmid",
    lastname: "Humphries",
    department: "HR Business Partner",
    position: "Assistant Manager-HR Business Partner",
    mobileNumber: "081-111-1111",
    workingLocation: "TPE - Rayong Site#1",
    company: "Thai Polyethylene Co., Ltd.",
    follower: 29078,
    following: 84392,
    authorities: ["ROLE_USER", "ROLE_ADMIN"],
  },
  {
    id: 2,
    username: "manager",
    email: "manager@scg.com",
    password: "managermanager",
    image: "manager.jpg",
    firstname: "Theodor",
    lastname: "O'Moore",
    department: "HR Business Partner",
    position: "Manager-HR Business Partner",
    mobileNumber: "082-222-2222",
    workingLocation: "TPE - Rayong Site#1",
    company: "Thai Polyethylene Co., Ltd.",
    follower: 86753,
    following: 32454,
    authorities: ["ROLE_USER", "ROLE_MANAGER"],
  },
  {
    id: 3,
    username: "user",
    email: "user@scg.com",
    password: "useruser",
    image: "user.jpg",
    firstname: "Shaunna",
    lastname: "Richard",
    department: "HDPE 4 Production",
    position: "HDPE 4 Production Operator",
    mobileNumber: "083-333-3333",
    workingLocation: "TPE - Rayong Site#3",
    company: "Thai Polyethylene Co., Ltd.",
    follower: 9732,
    following: 4356,
    authorities: ["ROLE_USER"],
  },
];
module.exports = Users;
